import solc from "solc";
import { readFileSync, writeFileSync } from "node:fs";
export function compile(extraSources = {}) {
  const input = {
    language: "Solidity",
    sources: {
      "InvoiceForwarder.sol": {
        content: readFileSync("contracts/InvoiceForwarder.sol", "utf8"),
      },
      ...extraSources,
    },
    settings: {
      optimizer: { enabled: true, runs: 200 },
      evmVersion: "shanghai",
      outputSelection: {
        "*": {
          "*": ["abi", "evm.bytecode.object", "evm.deployedBytecode.object"],
        },
      },
    },
  };
  const output = JSON.parse(
    solc.compile(JSON.stringify(input), {
      import: (path) => ({
        contents: readFileSync(`node_modules/${path}`, "utf8"),
      }),
    }),
  );
  const errors = output.errors?.filter((e) => e.severity === "error");
  if (errors?.length)
    throw new Error(errors.map((e) => e.formattedMessage).join("\n"));
  return output.contracts;
}
if (process.argv.includes("--write")) {
  const contracts = compile()["InvoiceForwarder.sol"];
  const out = Object.fromEntries(
    Object.entries(contracts).map(([name, c]) => [
      name,
      {
        abi: c.abi,
        bytecode: `0x${c.evm.bytecode.object}`,
        deployedBytecode: `0x${c.evm.deployedBytecode.object}`,
      },
    ]),
  );
  writeFileSync(
    "shared/invoiceForwarderArtifact.ts",
    `// Generated by bun run contracts:compile. Compiler 0.8.30, optimizer 200, Shanghai.\nexport const invoiceForwarderArtifact = ${JSON.stringify(out, null, 2)} as const;\n`,
  );
}
