import { isBillOverdue } from '../../../shared/dueDate';
export const wallet = '0x1111111111111111111111111111111111111111';
const now = Date.UTC(2026, 8, 4, 12);
export const org = {
  _id: 'demo',
  name: 'Northstar Studio',
  createdAt: now,
  updatedAt: now,
  screeningEnforcement: 'off',
  relayFeeMode: 'stablecoin_only',
  relayFeeTokenSymbol: 'USDC',
};
export const members = [
  {
    membershipId: 'm1',
    userId: 'user1',
    name: 'Alex Morgan',
    email: 'alex@northstar.co',
    walletAddress: wallet,
    role: 'admin',
    status: 'active',
  },
  {
    membershipId: 'm2',
    userId: 'user2',
    name: 'Jordan Lee',
    email: 'jordan@northstar.co',
    walletAddress: '0x2222222222222222222222222222222222222222',
    role: 'initiator',
    status: 'active',
    paymentPolicy: { token: 'USDC', perPayment: '5000', perMonth: '25000' },
  },
];
export const safes = [
  {
    _id: 'safe1',
    orgId: 'demo',
    safeAddress: '0x3333333333333333333333333333333333333333',
    chainId: 8453,
    threshold: 2,
    owners: [wallet, members[1].walletAddress],
    isActive: true,
    createdAt: now,
  },
];
export const customerInvoices = [
  { _id: 'ar1', orgId: 'demo', safeId: 'safe1', createdBy: 'user1', number: 'INV-2026-1042', customerName: 'Acme Studio', customerEmail: 'accounts@example.invalid', description: 'September design services. Thank you for working with us.', items: [{ description: 'Design services', quantity: 3, unitPrice: '500' }], token: 'USDC', tokenAddress: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', chainId: 8453, treasury: safes[0].safeAddress, amount: '1500', dueDate: now + 30 * 86400000, state: 'issued', publicToken: 'a'.repeat(64), receivingAddress: '0x4444444444444444444444444444444444444444', received: '500000000', forwarded: '0', lastCheckedAt: now, createdAt: now, updatedAt: now },
  { _id: 'ar2', orgId: 'demo', safeId: 'safe1', createdBy: 'user1', number: 'INV-2026-1043', customerName: 'Cedar Partners', description: '', items: [{ description: 'Monthly services', quantity: 1, unitPrice: '2000' }], token: 'USDC', tokenAddress: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', chainId: 8453, treasury: safes[0].safeAddress, amount: '2000', dueDate: now + 30 * 86400000, state: 'draft', received: '0', forwarded: '0', createdAt: now, updatedAt: now },
];
export const recipients = [
  ['Maya Chen', 'maya@northstar.co', 'individual', 'Engineering', 'ready'],
  ['James Okafor', 'james@northstar.co', 'individual', 'Operations', 'ready'],
  [
    'Studio North',
    'accounts@studionorth.co',
    'business',
    'Design partners',
    'ready',
  ],
  [
    'Sofia Garcia',
    'sofia@northstar.co',
    'individual',
    'Contractors',
    'incomplete',
  ],
  ['Linear Labs', 'finance@linearlabs.co', 'business', 'Software', 'ready'],
  ['Arjun Patel', 'arjun@northstar.co', 'individual', 'Engineering', 'ready'],
].map(([name, email, type, group, status], i) => ({
  _id: `r${i}`,
  orgId: 'demo',
  name,
  email,
  type,
  tags: [group],
  preferredToken: i === 5 ? 'USDT' : 'USDC',
  preferredChainId: 8453,
  walletAddress:
    status === 'ready' ? `0x${(i + 5).toString(16).repeat(40)}` : '',
  isActive: true,
  createdAt: now,
  updatedAt: now,
  payoutReviewStatus: status === 'ready' ? 'approved' : 'unreviewed',
  payoutVersion: status === 'ready' ? 1 : 0,
}));
const makePayment = (
  id: string,
  name: string,
  totalAmount: string,
  status: string,
  day: number,
  purpose = 'payroll',
) => ({
  _id: id,
  orgId: 'demo',
  safeId: 'safe1',
  chainId: 8453,
  type: 'batch',
  name,
  displayName: name,
  totalAmount,
  token: 'USDC',
  status,
  scheduledAt: Date.UTC(2026, 8, day, 12),
  createdAt: now,
  createdBy: 'user1',
  purpose,
  safeTxHash: status === 'draft' ? undefined : '0x' + 'ab'.repeat(32),
  beneficiary: { name: 'Team payment', walletAddress: '' },
  recurringPaymentId: id === 'p1' || id === 'p5' ? 'rec1' : undefined,
});
export const payments = [
  makePayment('p1', 'September contractor payroll', '28450', 'draft', 15),
  makePayment(
    'p2',
    'Product studio · September',
    '4800',
    'proposed',
    8,
    'invoice',
  ),
  makePayment('p3', 'Customer success team', '12600', 'pending', 10),
  makePayment('p4', 'Cloud infrastructure', '1250', 'failed', 5, 'invoice'),
  makePayment('p5', 'August contractor payroll', '27300', 'executed', 30),
  makePayment(
    'p6',
    'Design partner invoices',
    '8400',
    'executed',
    28,
    'invoice',
  ),
];
export const bills = [
  {
    _id: 'b1',
    beneficiaryId: 'r2',
    invoiceNumber: 'INV-2026-084',
    vendorName: 'Studio North',
    dueDate: now,
    amount: '4800',
    token: 'USDC',
    status: 'unpaid',
    description: 'Brand design and product support',
  },
  {
    _id: 'b2',
    beneficiaryId: 'r4',
    invoiceNumber: 'INV-3492',
    vendorName: 'Linear Labs',
    dueDate: now + 86400000,
    amount: '2250',
    token: 'USDC',
    status: 'unpaid',
  },
].map((b) => ({
  ...b,
  orgId: 'demo',
  createdBy: 'user1',
  createdAt: now,
  updatedAt: now,
}));
export const recurring = [
  {
    _id: 'rec1',
    orgId: 'demo',
    name: 'Contractor payroll',
    purpose: 'payroll',
    chainId: 8453,
    token: 'USDC',
    cadence: 'monthly',
    anchorDay: 15,
    nextPayDate: Date.UTC(2026, 9, 15, 12),
    status: 'active',
    version: 1,
    createdBy: 'user1',
    createdAt: now,
    totalAmount: '28450',
    recipients: [
      { beneficiaryId: 'r0', amount: '14225' },
      { beneficiaryId: 'r1', amount: '14225' },
    ],
  },
];
export const overview = {
  needsReview: 2,
  exceptionCount: 1,
  draftCount: 1,
  reviewedRecipients: 5,
  recipientsNeedReview: 1,
  exceptions: [{...payments[3], exceptionReason: "Payment failed"}],
  drafts: [payments[0]],
  plannedDebits: [{safeId:"safe1", token:"USDC", amount:"47100"}],
  plansIncomplete: false,
  unquotedFees: true,
  scheduledCount: 3,
  overdueBills: bills.filter(b => isBillOverdue(b.dueDate, Date.now())).length,
  incompleteRecipients: 1,
  recipientCount: 6,
  accountCount: 1,
  limitedHistory: false,
  review: payments.slice(1, 3),
  upcoming: payments.slice(0, 3).sort((a, b) => a.scheduledAt - b.scheduledAt),
  recent: payments.slice(4),
  bills,
};
